#include "images.h"

const ext_img_desc_t images[30] = {
    { "ok", &img_ok },
    { "ch_no_active", &img_ch_no_active },
    { "dhw_no_active", &img_dhw_no_active },
    { "ch_active", &img_ch_active },
    { "ch_off", &img_ch_off },
    { "dhw_active", &img_dhw_active },
    { "dhw_off", &img_dhw_off },
    { "err", &img_err },
    { "flame", &img_flame },
    { "hot", &img_hot },
    { "lock", &img_lock },
    { "settings", &img_settings },
    { "sos", &img_sos },
    { "temp", &img_temp },
    { "time", &img_time },
    { "trable", &img_trable },
    { "w4", &img_w4 },
    { "w0", &img_w0 },
    { "w1", &img_w1 },
    { "w2", &img_w2 },
    { "w3", &img_w3 },
    { "w5", &img_w5 },
    { "w6", &img_w6 },
    { "w7", &img_w7 },
    { "q1", &img_q1 },
    { "q2", &img_q2 },
    { "q3", &img_q3 },
    { "q7", &img_q7 },
    { "w8", &img_w8 },
    { "w9", &img_w9 },
};
